spring:
  datasource:
    url: ${DATABASE_URL}  # 운영 MySQL DB URL
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update  # 운영은 스키마 업데이트
    properties:
      hibernate:
        show_sql: false  # 운영에서는 SQL 로그 비활성

  data:
    redis:
      host: ${REDIS_HOST}  # Redis 호스트
      password: ${REDIS_PASSWORD}  # Redis 패스워드

springdoc:
  swagger-ui:
    enabled: false  # 운영 Swagger UI 비활성

logging:
  level:
    com.back: INFO
    root: WARN  # 기본 로그 레벨

custom:
  cookie:
    secure: true  # HTTPS만 허용
    same: "None"
  site:
    cookieDomain: "${BASE_URL}"
    frontUrl: "${custom.prod.frontUrl}"
    backUrl: "${custom.prod.backUrl}"
    name: ssoul
