spring:
  datasource:
    driver-class-name: org.h2.Driver  # H2 DB ????
    url: jdbc:h2:./db_dev;MODE=MySQL  # H2 DB ?? ? MySQL ?? ??
    username: sa
    password:

  h2:
    console:
      enabled: true  # H2 ? ?? ???
      path: /h2-console  # ?? ?? ??

  jpa:
    defer-datasource-initialization: true  # ??? ??
    database-platform: org.hibernate.dialect.H2Dialect  # H2 Dialect
    hibernate:
      ddl-auto: create-drop  # ?? ? ??? ??, ?? ? ??
    properties:
      hibernate:
        format_sql: true  # SQL ???
        show_sql: true  # SQL ?? ??

  sql:
    init:
      mode: always  # ?? ??? ???? ??
      encoding: UTF-8
      data-locations: classpath:data-h2.sql  # ?? ??? SQL

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method  # Swagger ?? ??

logging:
  level:
    org.hibernate.orm.jdbc.bind: TRACE
    org.hibernate.orm.jdbc.extract: TRACE
    org.springframework.transaction.interceptor: TRACE
    com.back: DEBUG  # ??? ??? ??

custom:
  cookie:
    secure: false  # ??? HTTP ??
    same: "Lax"
